
# H2 Configurations
spring.datasource.url=jdbc:h2:file:~/Projects/Spring/MusicRecordsSpring/h2database/musicrecords
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=username
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.path=/h2console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false
